AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Stack
Parameters:
  AuthName:
    Type: String
    Description: Unique Auth Name for Cognito Resources

Resources:
  
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${AuthName}-user-pool
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: false
  
  # Creates a User Pool Client to be used by the identity pool
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub ${AuthName}-client
      GenerateSecret: false
      UserPoolId: !Ref UserPool
  
  # AdminUser:
  #   Type: AWS::Cognito::UserPoolUser
  #   Properties: 
  #     ClientMetadata: Json
  #     DesiredDeliveryMediums: 
  #       - email
  #     ForceAliasCreation: True
  #     MessageAction: "SUPPRESS"
  #     UserAttributes: 
  #       - email_verified: True
  #       - Name: "email"
  #         Value: "chlmes@amazon.com"
  #       - Name: "Name"
  #         Value: "Chris Holmes"
  #     Username: chlmes@amazon.com
  #     UserPoolId: !Ref UserPool
  #     ValidationData: 
  #       - AttributeType

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: "UserPool::Id"
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: "UserPoolClient::Id"
